In [1]:
import os

In [3]:
os.chdir('/run/media/abhi/0B8B16F90B8B16F9/git-repos/accent-classification-deep-learning/recordings/recordings/')

In [5]:
import numpy as np

In [7]:
X = np.load('X.npy')

In [9]:
y = np.load('y.npy')

In [10]:
X.shape

(329, 20, 85)

In [11]:
y[:10]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
y[-10:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
p = np.random.permutation(len(X))
X =  X[p]
y = y[p]

In [15]:
y[:10]

array([1, 0, 2, 0, 1, 2, 2, 0, 0, 0])

In [16]:
X_train = X[:250]
y_train = y[:250]

In [17]:
X_test = X[250:]
y_test = y[250:]

In [22]:
import tensorflow as tf
# from tf.keras.optimizers import SGD
import sklearn
 
# np.random.seed(1337)  # for reproducibility
# import tf.keras.preprocessing.sequence # import sequence
# import tf.keras.utils.np_utils # import np_utils
# import tf.keras.models.Sequential # import Sequential
# import tf.keras.layers.core.Dense # import Dense, Dropout, Activation
# import tf.keras.layers.core.Dropout
# import tf.keras.layers.core.Activation
# import tf.keras.layers.recurrent.LSTM # import LSTM


In [24]:
test_dim = 2999
maxlen = 100
batch_size = 30
nb_filter = 64
filter_length_1 = 50
filter_length_2 = 25
hidden_dims = 250
nb_epoch = 8
nb_classes = 3

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [36]:
model = tf.keras.models.Sequential()
# model = tf.expand_dims(model, axis=-1)
model.add(tf.keras.layers.LSTM(32, return_sequences=True, stateful=False))
model.add(tf.keras.layers.LSTM(20))

model.add(tf.keras.layers.Dense(nb_classes, activation='softmax'))


model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])

print("Train...")
model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=5, validation_data=(X_test, y_test))


Train...


ValueError: in user code:

    /usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:505 train_function  *
        outputs = self.distribute_strategy.run(
    /usr/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:466 train_step  **
        loss = self.compiled_loss(
    /usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:204 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /usr/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    /usr/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    /usr/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:1527 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /usr/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4561 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /usr/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 3) are incompatible


In [ ]:
y_pred=model.predict_classes(X_test, batch_size=batch_size)
print(classification_report(y_test, y_pred))

In [37]:
classifier = tf.keras.models.Sequential()
classifier.add(tf.keras.layers.Dense(units=6, kernel_initializer='glorot_uniform',activation='relu'))

#adding second and third hidden layer
classifier.add(tf.keras.layers.Dense(units=6, kernel_initializer='glorot_uniform',activation='relu'))
classifier.add(tf.keras.layers.Dense(units=6, kernel_initializer='glorot_uniform',activation='relu'))


#adding output layer
classifier.add(tf.keras.layers.Dense(units=1, kernel_initializer='glorot_uniform',activation='sigmoid'))

#compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#fitting the ANN to traing set
classifier.fit(X_train, y_train, batch_size=20, epochs=500)

#prediction
y_pred = classifier.predict(X_test)
y_pred =(y_pred > 0.5)

Epoch 1/500
13/13 [==============================] - 0s 4ms/step - loss: 2.4474 - accuracy: 0.3026
Epoch 2/500
13/13 [==============================] - 0s 5ms/step - loss: 1.6929 - accuracy: 0.2668
Epoch 3/500
13/13 [==============================] - 0s 5ms/step - loss: 1.4986 - accuracy: 0.2534
Epoch 4/500
13/13 [==============================] - 0s 7ms/step - loss: 1.2915 - accuracy: 0.2452
Epoch 5/500
13/13 [==============================] - 0s 6ms/step - loss: 1.1921 - accuracy: 0.2380
Epoch 6/500
13/13 [==============================] - 0s 5ms/step - loss: 1.0121 - accuracy: 0.2356
Epoch 7/500
13/13 [==============================] - 0s 5ms/step - loss: 0.8540 - accuracy: 0.2348
Epoch 8/500
13/13 [==============================] - 0s 5ms/step - loss: 0.8775 - accuracy: 0.2298
Epoch 9/500
13/13 [==============================] - 0s 4ms/step - loss: 0.7566 - accuracy: 0.2258
Epoch 10/500
13/13 [==============================] - 0s 4ms/step - loss: 0.6692 - accuracy: 0.2214
Epoch 11/

13/13 [==============================] - 0s 4ms/step - loss: 0.0240 - accuracy: 0.2038
Epoch 84/500
13/13 [==============================] - 0s 4ms/step - loss: 0.0500 - accuracy: 0.2038
Epoch 85/500
13/13 [==============================] - 0s 3ms/step - loss: 0.0399 - accuracy: 0.2036
Epoch 86/500
13/13 [==============================] - 0s 3ms/step - loss: 0.0651 - accuracy: 0.2034
Epoch 87/500
13/13 [==============================] - 0s 3ms/step - loss: 0.0767 - accuracy: 0.2022
Epoch 88/500
13/13 [==============================] - 0s 4ms/step - loss: 0.0352 - accuracy: 0.2042
Epoch 89/500
13/13 [==============================] - 0s 4ms/step - loss: 0.0529 - accuracy: 0.2050
Epoch 90/500
13/13 [==============================] - 0s 4ms/step - loss: -0.0122 - accuracy: 0.2040
Epoch 91/500
13/13 [==============================] - 0s 3ms/step - loss: 0.0164 - accuracy: 0.2040
Epoch 92/500
13/13 [==============================] - 0s 4ms/step - loss: 0.0367 - accuracy: 0.2034
Epoch 93/500

13/13 [==============================] - 0s 4ms/step - loss: -0.2032 - accuracy: 0.2136
Epoch 164/500
13/13 [==============================] - 0s 4ms/step - loss: -0.2316 - accuracy: 0.2152
Epoch 165/500
13/13 [==============================] - 0s 4ms/step - loss: -0.2681 - accuracy: 0.2104
Epoch 166/500
13/13 [==============================] - 0s 5ms/step - loss: -0.3014 - accuracy: 0.2150
Epoch 167/500
13/13 [==============================] - 0s 4ms/step - loss: -0.2554 - accuracy: 0.2156
Epoch 168/500
13/13 [==============================] - 0s 4ms/step - loss: -0.3101 - accuracy: 0.2130
Epoch 169/500
13/13 [==============================] - 0s 4ms/step - loss: -0.3589 - accuracy: 0.2132
Epoch 170/500
13/13 [==============================] - 0s 3ms/step - loss: -0.3075 - accuracy: 0.2134
Epoch 171/500
13/13 [==============================] - 0s 3ms/step - loss: -0.3033 - accuracy: 0.2140
Epoch 172/500
13/13 [==============================] - 0s 4ms/step - loss: -0.2986 - accuracy: 0

13/13 [==============================] - 0s 4ms/step - loss: -0.4429 - accuracy: 0.2208
Epoch 244/500
13/13 [==============================] - 0s 4ms/step - loss: -0.4908 - accuracy: 0.2184
Epoch 245/500
13/13 [==============================] - 0s 2ms/step - loss: -0.6182 - accuracy: 0.2208
Epoch 246/500
13/13 [==============================] - 0s 3ms/step - loss: -0.5186 - accuracy: 0.2194
Epoch 247/500
13/13 [==============================] - 0s 3ms/step - loss: -0.5870 - accuracy: 0.2192
Epoch 248/500
13/13 [==============================] - 0s 4ms/step - loss: -0.5275 - accuracy: 0.2176
Epoch 249/500
13/13 [==============================] - 0s 3ms/step - loss: -0.5917 - accuracy: 0.2214
Epoch 250/500
13/13 [==============================] - 0s 3ms/step - loss: -0.5474 - accuracy: 0.2202
Epoch 251/500
13/13 [==============================] - 0s 3ms/step - loss: -0.6420 - accuracy: 0.2180
Epoch 252/500
13/13 [==============================] - 0s 3ms/step - loss: -0.6021 - accuracy: 0

13/13 [==============================] - 0s 3ms/step - loss: -0.6414 - accuracy: 0.2176
Epoch 324/500
13/13 [==============================] - 0s 3ms/step - loss: -0.6777 - accuracy: 0.2296
Epoch 325/500
13/13 [==============================] - 0s 3ms/step - loss: -0.7032 - accuracy: 0.2298
Epoch 326/500
13/13 [==============================] - 0s 3ms/step - loss: -0.7192 - accuracy: 0.2236
Epoch 327/500
13/13 [==============================] - 0s 4ms/step - loss: -0.6949 - accuracy: 0.2242
Epoch 328/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7160 - accuracy: 0.2212
Epoch 329/500
13/13 [==============================] - 0s 5ms/step - loss: -0.6954 - accuracy: 0.2234
Epoch 330/500
13/13 [==============================] - 0s 6ms/step - loss: -0.7334 - accuracy: 0.2288
Epoch 331/500
13/13 [==============================] - 0s 5ms/step - loss: -0.7117 - accuracy: 0.2244
Epoch 332/500
13/13 [==============================] - 0s 5ms/step - loss: -0.6658 - accuracy: 0

13/13 [==============================] - 0s 5ms/step - loss: -0.7565 - accuracy: 0.2304
Epoch 404/500
13/13 [==============================] - 0s 5ms/step - loss: -0.7274 - accuracy: 0.2280
Epoch 405/500
13/13 [==============================] - 0s 3ms/step - loss: -0.6299 - accuracy: 0.2338
Epoch 406/500
13/13 [==============================] - 0s 3ms/step - loss: -0.6759 - accuracy: 0.2338
Epoch 407/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7546 - accuracy: 0.2326
Epoch 408/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7410 - accuracy: 0.2256
Epoch 409/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7179 - accuracy: 0.2400
Epoch 410/500
13/13 [==============================] - 0s 3ms/step - loss: -0.7576 - accuracy: 0.2278
Epoch 411/500
13/13 [==============================] - 0s 3ms/step - loss: -0.7407 - accuracy: 0.2326
Epoch 412/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7945 - accuracy: 0

13/13 [==============================] - 0s 5ms/step - loss: -0.8866 - accuracy: 0.2476
Epoch 484/500
13/13 [==============================] - 0s 4ms/step - loss: -0.8288 - accuracy: 0.2408
Epoch 485/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7681 - accuracy: 0.2372
Epoch 486/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7305 - accuracy: 0.2336
Epoch 487/500
13/13 [==============================] - 0s 5ms/step - loss: -0.8177 - accuracy: 0.2364
Epoch 488/500
13/13 [==============================] - 0s 3ms/step - loss: -0.8710 - accuracy: 0.2494
Epoch 489/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7870 - accuracy: 0.2204
Epoch 490/500
13/13 [==============================] - 0s 4ms/step - loss: -0.7726 - accuracy: 0.2426
Epoch 491/500
13/13 [==============================] - 0s 4ms/step - loss: -0.8414 - accuracy: 0.2288
Epoch 492/500
13/13 [==============================] - 0s 5ms/step - loss: -0.7481 - accuracy: 0